In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_t_minus_1 = np.array([0.333, 0, 0.333, 0, 0, 0, 0, 0.333, 0, 0])

In [3]:
x_t_perfect = np.zeros((10,1))
for i in range(10):
    x_t_perfect[i] = x_t_minus_1[i - 2]
print(x_t_perfect)

[[0.   ]
 [0.   ]
 [0.333]
 [0.   ]
 [0.333]
 [0.   ]
 [0.   ]
 [0.   ]
 [0.   ]
 [0.333]]


In [4]:
y = x_t_perfect[:,0]

In [5]:
y.shape

(10,)

In [6]:
x_t_perfect.shape

(10, 1)

In [7]:
y

array([0.   , 0.   , 0.333, 0.   , 0.333, 0.   , 0.   , 0.   , 0.   ,
       0.333])

In [8]:
x_t_perfect[0][0]

0.0

In [9]:
y[0]

0.0

In [10]:
state_transition_prob = np.array([[0, 0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0],
                                  [0, 0, 0.1, 0.8, 0.1, 0, 0, 0, 0, 0],
                                  [0, 0, 0, 0.1, 0.8, 0.1, 0, 0, 0, 0],
                                  [0, 0, 0, 0, 0.1, 0.8, 0.1, 0, 0, 0],
                                  [0, 0, 0, 0, 0, 0.1, 0.8, 0.1, 0, 0],
                                  [0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1, 0],
                                  [0, 0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1],
                                  [0.1, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.8],
                                  [0.8, 0.1, 0, 0, 0, 0, 0, 0, 0, 0.1],
                                  [0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
state_transition_prob.T

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1],
       [0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.8],
       [0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1],
       [0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. ]])

In [12]:
x_t_slow = np.zeros((10,1))

In [13]:
np.dot(state_transition_prob.T,x_t_minus_1)

array([0.0333, 0.0333, 0.2664, 0.0666, 0.2664, 0.0333, 0.    , 0.    ,
       0.0333, 0.2664])

In [14]:
np.dot(state_transition_prob,x_t_minus_1)

array([0.2664, 0.0333, 0.    , 0.    , 0.0333, 0.2664, 0.0333, 0.0333,
       0.2664, 0.0666])

In [15]:
u = 1
n = 10
px = np.ones((n,n)) / (n * n)
px

array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]])

In [16]:
px[0][0]

0.01

In [17]:
r,c = px.shape
r

10

In [18]:
mark=np.array(([4,4],[4,6],[4,8],[6,8],[8,8]))
mark_x_1 = np.array(([3,4],[3,6],[3,8],[5,8],[7,8]))

In [19]:
np.array(([4,1])) in mark

True

In [20]:
np.array(([4,1]))

array([4, 1])

In [21]:
LL= np.zeros((10,10))
LL.shape[0]

10

In [22]:
i,j = mark[0]
i

4

In [23]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [24]:
x_loc=0
x_1_loc=0
for i in range(LL.shape[0]):      
    for j in range(LL.shape[0]):
        if(x_loc<len(mark)):
            r,c = mark[x_loc]
        if(x_1_loc<len(mark_x_1)):
            r1,c1 = mark_x_1[x_1_loc]            
        if(i == r1) and (j==c1):
            LL[i][j] = 0.25
            x_1_loc+=1
        elif(i == r) and (j==c):
            LL[i][j] = 0.7
            x_loc+=1           
        else:
            LL[i][j] = 0.05
        
            
LL

array([[0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.25, 0.05, 0.25, 0.05, 0.25, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.7 , 0.05, 0.7 , 0.05, 0.7 , 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.25, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.7 , 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.25, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.7 , 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]])

In [25]:
u=1
r_rt, c_rt = LL.shape
for i in range(LL.shape[0]):
    for j in range(LL.shape[1]):
        LL[i,(j+u)%c_rt] *= 0.6
        LL[i,(j+u-1)%c_rt] *= 0.1
        LL[i,(j+u+1)%c_rt] *= 0.1
        LL[(i-1)%r_rt,(j+u)%c_rt] *= 0.1
        LL[(i+1)%r_rt,(j+u)%c_rt] *= 0.1
LL

array([[3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06,
        3.0e-06, 3.0e-06, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06,
        3.0e-06, 3.0e-06, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06,
        3.0e-06, 3.0e-06, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 1.5e-05, 3.0e-06, 1.5e-05,
        3.0e-06, 1.5e-05, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 4.2e-05, 3.0e-06, 4.2e-05,
        3.0e-06, 4.2e-05, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06,
        3.0e-06, 1.5e-05, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06,
        3.0e-06, 4.2e-05, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06,
        3.0e-06, 1.5e-05, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06, 3.0e-06,
        3.0e-06, 4.2e-05, 3.0e-06],
       [3.0e-06, 3.0e-06, 3.0e-06, 3.

In [26]:
x=0
for i in range(LL.shape[0]):      
    for j in range(LL.shape[0]):
        if(x<len(mark)):
            r,c = mark[x] 
        if(i == r) and (j==c):
            LL[i-1][j] = 0.7
            x+=1
        else:
            LL[i][j] = 0.25
        
            
LL

array([[2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01,
        2.5e-01, 2.5e-01, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01,
        2.5e-01, 2.5e-01, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01,
        2.5e-01, 2.5e-01, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 7.0e-01, 2.5e-01, 7.0e-01,
        2.5e-01, 7.0e-01, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 4.2e-05, 2.5e-01, 4.2e-05,
        2.5e-01, 4.2e-05, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01,
        2.5e-01, 7.0e-01, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01,
        2.5e-01, 4.2e-05, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01,
        2.5e-01, 7.0e-01, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01, 2.5e-01,
        2.5e-01, 4.2e-05, 2.5e-01],
       [2.5e-01, 2.5e-01, 2.5e-01, 2.

In [27]:
markerIndex=0
z_false_det_marker = 0.25
z_true_det_marker = 0.70
odds = z_true_det_marker / z_false_det_marker
for i in range(LL.shape[0]):      
    for j in range(LL.shape[0]):
        if(markerIndex<len(mark)):
            r,c = mark[markerIndex] 
        if(i == r) and (j==c):
            LL[i][j] *= odds
            markerIndex+=1
        else:
            LL[i][j] = z_false_det_marker
LL

array([[2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01,
        2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01],
       [2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01,
        2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01],
       [2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01,
        2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01],
       [2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01,
        2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01],
       [2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 1.176e-04, 2.500e-01,
        1.176e-04, 2.500e-01, 1.176e-04, 2.500e-01],
       [2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01,
        2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01],
       [2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01,
        2.500e-01, 2.500e-01, 1.176e-04, 2.500e-01],
       [2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01, 2.500e-01,
        2.500e-01, 2.500e-01, 2.500e-

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
dt = 0.1
F = np.array([[1, dt, 0, 0], [0, 1, 0, 0], [0, 0, 1, dt], [0 , 0, 0, 1]]) # State transition Matrix
B = np.eye(4) # Control change Matrix
G = 9.8
X = np.zeros((4,1))
X_new = np.dot(F,X)+np.dot(B,G)
X_new

array([[9.8, 0. , 0. , 0. ],
       [0. , 9.8, 0. , 0. ],
       [0. , 0. , 9.8, 0. ],
       [0. , 0. , 0. , 9.8]])